
default_platform(:ios)

platform :ios do
  before_all do
    unlock_keychain(path: 'login') if ENV['FL_UNLOCK_KEYCHAIN_PASSWORD']

    Dotenv.load ".env.ios"
  end

  desc "Take care of signing"
  lane :signing do
    sync_code_signing #match

    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]

    update_code_siging_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
	  signing
    build_ios_app #gym
  end

  desc "release build"
  lane :release do
    ensure_git_status_clean
    ensure_git_branch
	  build
    upload_to_app_store #delivery

    reset_git_repo
  end
end
